yolo_model:

  config_file:
    name: forward_ver4_tiny.cfg
  weight_file:
    name: forward_ver4_tiny.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - green
      - left
      - red
      - straightleft
      - yellow
