yolo_model:

  config_file:
    name: forward_ver2.cfg
  weight_file:
    name: forward_ver2.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - green
      - left
      - red
      - straightleft
      - yellow
      - person
      - car
