yolo_model:

  config_file:
    name: yolo_ver4.cfg
  weight_file:
    name: yolo_ver4.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - A1
      - A2
      - A3
      - B1
      - B2
      - B3
      - green
      - left
      - red
      - straightleft
      - yellow
      - person
      - car
      - uturn
      - kidzone
      - parking
      - stopline
