// Generated by gencpp from file object_msgs/Control.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_CONTROL_H
#define OBJECT_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace object_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : header()
    , accel(0.0)
    , kappa(0.0)
    , delta(0.0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , accel(0.0)
    , kappa(0.0)
    , delta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _accel_type;
  _accel_type accel;

   typedef float _kappa_type;
  _kappa_type kappa;

   typedef float _delta_type;
  _delta_type delta;





  typedef boost::shared_ptr< ::object_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::object_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::object_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::object_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::Control_<ContainerAllocator1> & lhs, const ::object_msgs::Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.accel == rhs.accel &&
    lhs.kappa == rhs.kappa &&
    lhs.delta == rhs.delta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::Control_<ContainerAllocator1> & lhs, const ::object_msgs::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8115ca7991121375827392e805ee858f";
  }

  static const char* value(const ::object_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8115ca7991121375ULL;
  static const uint64_t static_value2 = 0x827392e805ee858fULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/Control";
  }

  static const char* value(const ::object_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 accel  # m/ss\n"
"float32 kappa  # 1/m\n"
"float32 delta  # radian\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::object_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.accel);
      stream.next(m.kappa);
      stream.next(m.delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "accel: ";
    Printer<float>::stream(s, indent + "  ", v.accel);
    s << indent << "kappa: ";
    Printer<float>::stream(s, indent + "  ", v.kappa);
    s << indent << "delta: ";
    Printer<float>::stream(s, indent + "  ", v.delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_CONTROL_H
